// utils/categories.ts
export const CATEGORIES = [
    'Business & Finance',
    'Technology & Programming',
    'Science & Education',
    'Arts & Culture',
    'Health & Fitness',
    'Cooking & Nutrition',
    'Travel & Adventure',
    'Music & Entertainment',
    'Politics & Current Events',
    'Sports & Recreation',
    'Personal Development',
    'Philosophy & Psychology',
    'History & Documentaries',
    'Language Learning',
    'DIY & Crafts',
    'Gaming',
    'Fashion & Beauty',
    'Spirituality & Religion',
    'Environmental & Sustainability',
    'Parenting & Family',
    'Career & Professional Development',
    'Automotive & Transportation',
    'Home & Garden',
    'Pet Care & Animals',
    'Comedy & Humor',
    'Photography & Videography',
    'Literature & Writing',
    'Entrepreneurship & Startups',
    'Social Issues & Activism',
    'Miscellaneous'
];